### ISSUE TITLE
deps: upgrade dependencies

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1854]
As part of the 23.1 release cycle, we should look at bumping some of our direct dependencies. While the set of deps in Pebble is relatively small, some are used often in hot paths (i.e. those responsible for compression and hashing), and it's nice to pick up upstream improvements.

Jira issue: PEBBLE-160

**Comment by nicktrav** [comment]
A word of caution for whoever picks this up - #1706 would need to be resolved in order to update our zstd deps.

**Comment by nicktrav** [comment]
The 23.1 release might be good a good time to consider ripping out the `vendor/` directory and associated `mod` directives (i.e. do away with `go -mod=vendor ...` in the makefile, etc.).

I checked with our dev-inf friends about the implications for Cockroach ([link](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1659474808056339)), and it seems like this should be fine.

**Comment by cristaloleg** [comment]
Hi, should this be solved by a minimal [Dependabot](https://github.com/dependabot) config? By example:

```yaml
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
```

(or without Github Actions 🤷 )
